# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.3.7
_src_path: https://github.com/wabenet/project-template
archetype: other
archetype_other: plugin
components: []
description: Adds support for the Docker daemon as a dodo runtime plugin.
lifecycle: production
name: docker

