---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dodo-docker
  description: Adds support for the Docker daemon as a dodo runtime plugin.

spec:
  type: library
  lifecycle: production
  owner: ole.claussen@wabenet.com
