---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: wabenet/project-template/actions/build@v0.3.7
        with:
          go-version: "1.24"

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: wabenet/project-template/actions/coverage@v0.3.7
        with:
          go-version: "1.24"
          cc-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
