---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "wabenet/wabe-project-build:v0.3.11"
      options: --user runner
    steps:
      - uses: wabenet/project-template/actions/build@v0.3.11

  coverage:
    runs-on: ubuntu-latest
    container:
      image: "wabenet/wabe-project-build:v0.3.11"
      options: --user runner
    steps:
      - uses: wabenet/project-template/actions/coverage@v0.3.11
        with:
          cc-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
