---
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: wabenet/project-template/actions/build@v0.3.7
        with:
          go-version: "1.24"
          release: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
